# Generated by Django 3.2.6 on 2021-09-14 18:04

import Account.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('age', models.PositiveSmallIntegerField(null=True, verbose_name='سن')),
                ('n_code', models.CharField(max_length=10, validators=[Account.utils.check_is_digit], verbose_name='کدملی')),
                ('phone', models.CharField(max_length=11, validators=[Account.utils.check_is_digit], verbose_name='شماره تماس')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='درباره ی من')),
                ('gender', models.CharField(choices=[('f', 'خانم'), ('m', 'آقا'), ('o', 'دیگری')], default='o', max_length=1, verbose_name='جنسیت')),
                ('is_writer', models.BooleanField(default=False, verbose_name=' نویسنده ')),
                ('cv', models.FileField(upload_to=Account.utils.profile_files_path, verbose_name=' فایل رزومه')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='نام کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل ها',
                'ordering': ['-m_time'],
            },
        ),
    ]
