# Generated by Django 3.2.6 on 2021-09-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'تایید'), (2, 'در حال بررسی'), (0, 'عدم تایید')], default=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='post',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'تایید'), (2, 'در حال بررسی'), (0, 'عدم تایید')], default=1, verbose_name='وضعیت'),
        ),
    ]
