# Generated by Django 3.2.6 on 2021-09-18 23:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20210918_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='co_des',
            field=ckeditor.fields.RichTextField(verbose_name='توضیحات کامل'),
        ),
    ]
